### ISSUE TITLE
Add a screenshot of the Things Web GUI

### ISSUE THREAD

**Issue by AlexanderWillner** [nicolai86/things-cloud-sdk#3]

**Comment by AlexanderWillner** [comment]
Alternatively, provide a guide like this one to start the GUI (which is not working):

```
#!/bin/bash

brew install go-statik bower

export GOPATH="$(PWD)"
export THINGS_USERNAME='login@example.org'
export THINGS_PASSWORD='password'

go get github.com/nicolai86/things-cloud-sdk
go get github.com/rakyll/statik/fs

cd "$GOPATH"/src/github.com/nicolai86/things-cloud-sdk/example/
go run main.go

cd "$GOPATH"/src/github.com/nicolai86/things-cloud-sdk/cmd/thingsweb
bower install webcomponents/webcomponentsjs --save
polymer build
go generate
go build
polymer serve &
pid=$!
open http://127.0.0.1:8081/components/things-web/
echo "Press enter to stop GUI"; read
kill "$pid"
```

**Comment by nicolai86** [comment]
The above script is actually quite close:

1. clone the repository. This is required because I don't serve a prebuild binary with all the assets.

```
git clone github.com/nicolai86/things-cloud-sdk
```

now you have two options: for development, install and run polymer serve:

```
cd /path/to/things-cloud-sdk/cmd/thingsweb
npm install 
bower install
polymer serve
```

last, start thingsweb in development mode:

```
$ go run main.go state.go -store /tmp/state -password <password> -username <username> -area <an-area>
```

open `http://localhost:8080/public`

if you instead compile you can use go-generate to create a binary with the latest assets compiled into the binary.

It looks like this:

<img width="952" alt="Screenshot 2019-04-18 at 19 13 18" src="https://user-images.githubusercontent.com/111324/56401507-0c7b9280-620e-11e9-86b9-8a31be053f8f.png">
